### ISSUE TITLE
Add storybooks for charts library

### ISSUE THREAD

**Issue by pjm17971** [esnet/react-timeseries-charts#423]
# 🌈Feature request

**What is this feature?**

Given the number of requests, PRs and the still pending work to move this code to typescript, a blocker on all that is confidence in changes. In the past the library was small enough that the examples code was that confidence. A first step to regain that confidence is to start to build a library of [storybook](https://storybook.js.org/) examples, potentially with snapshot tests, so that we can start to move this library forward again.

**How should the feature work?**

I've created a branch and setup the bare minimum for this. After that is merged, myself, potentially others at ESnet, and hopefully outside helpers can fill in that library with examples highlighting both existing functional behavior as well as examples of places where we'd like to improve the code.

**Branch**

The branch this work is happening on is:
https://github.com/esnet/react-timeseries-charts/tree/storybook

**Help needed**

If anyone has extensive experience with storybook and contribute to the setup (ideally this could be a source of documentation and testing), let me know or jump right in with a PR to the branch.

**TODO**

 - [X] Update project dependencies (esp webpack etc) so that storybook will work
 - [X] Create basic examples of storybook to get the ball rolling here
 - [X] Push to initial branch
 ... other
